### PR TITLE
Added OpenDaylight barclamp

### PR DESCRIPTION
**Pull request by mmnelemane**
Moved OpenDaylight barclamp from crowbar-opendaylight to crowbar-nfv.

### CODE REVIEW

**Comment by hwoarang** [comment]
The code in the old crowbar-opendaylight and this pull request is not the same. Please double check

**Comment by rsalevsky** [comment]
Why not just a simple rename?

**Comment by mmnelemane** [comment]
@rsalevsky: That makes sense to me. @hwoarang, @nkukreja: Can we do that ?

**Comment by hwoarang** [comment]
fine by me.

**Comment by mmnelemane** [comment]
Closing the pull request. Renaming the original opendaylight barclamp will fix this.

**Pull request closed without merging**
